---
grace-period: 60s

proxy:
  addr: localhost:3000
  reject-clients: true
  retry-after-interval: 3s
  block-poll-interval: 100ms
  close-poll-interval: 100ms

  tls:
    ca-cert: ca.pem
    cert: cert.pem
    key: key.pem

control:
  addr: localhost:3001

upstream:
  addr: localhost:3002
